### PANDAS DATAFRAME ASSIGNMENT

##### Easy (Basic and Selection)

In [94]:
from gc import get_threshold

# 1 Display the first 5 rows of the dataset.
import pandas as pd

df = pd.read_csv('customer_info.csv')

In [95]:
df.head(5)

,name,age,gender,region,premium_amount,claim_amount,tenure_years,policy_type,no_of_claims
0,John Patel,34,Male,Ontario,820.00,0.00,3,car,0
1,Sarah Wong,29,Female,British Columbia,650.50,1200.75,5,health,3
2,Michael Singh,45,Male,Alberta,1100.25,0.00,8,home,0
3,Priya Sharma,38,Female,Ontario,590.40,500.10,2,life,2
4,David Brown,52,Male,Manitoba,1400.90,3000.00,10,health,4

In [96]:
# 2 show all column names and data types.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            48 non-null     str
 1   age             48 non-null     int64
 2   gender          48 non-null     str
 3   region          48 non-null     str
 4   premium_amount  48 non-null     float64
 5   claim_amount    48 non-null     float64
 6   tenure_years    48 non-null     int64
 7   policy_type     48 non-null     str
 8   no_of_claims    48 non-null     int64
dtypes: float64(2), int64(3), str(4)
memory usage: 3.5 KB

In [97]:
# 3. Display only the columns Name, Age, reigon
selected_cols = ["name",'age','region']
df.loc[:,selected_cols].head(10)

            name  age            region
0     John Patel   34           Ontario
1     Sarah Wong   29  British Columbia
2  Michael Singh   45           Alberta
3   Priya Sharma   38           Ontario
4    David Brown   52          Manitoba
5    Emily Clark   27            Quebec
6      Jason Lee   41      Saskatchewan
7     Aisha Khan   33           Ontario
8  Robert Miller   56           Alberta
9   Linda Garcia   48       Nova Scotia

In [98]:
# 4 retrieve all rows where the region is ontario,

df.loc[df["region"] == 'Ontario', :].head(10)

,name,age,gender,region,premium_amount,claim_amount,tenure_years,policy_type,no_of_claims
0,John Patel,34,Male,Ontario,820.00,0.0,3,car,0
3,Priya Sharma,38,Female,Ontario,590.40,500.1,2,life,2
7,Aisha Khan,33,Female,Ontario,540.75,0.0,4,home,0
10,Kevin Turner,31,Male,Ontario,720.10,0.0,2,life,0
13,Olivia Martin,28,Female,Ontario,650.50,0.0,1,car,0
17,Hannah Scott,30,Female,Ontario,700.00,0.0,2,health,0
20,Liam Parker,42,Male,Ontario,1120.00,0.0,7,car,0
23,Isabella Moore,33,Female,Ontario,580.00,0.0,3,home,0
27,Ella King,35,Female,Ontario,660.40,0.0,4,home,0
29,Grace Hall,31,Female,Ontario,690.00,0.0,2,health,0

In [99]:
# 5 Count how many Male and Female customers exist.
df["gender"].value_counts()

gender
Male      24
Female    24
Name: count, dtype: int64

##### Basic /filtering and new columns

In [100]:
# 6 filter all customers whos premium_amount > 700
df.loc[df["premium_amount"] >700].head(10)

,name,age,gender,region,premium_amount,claim_amount,tenure_years,policy_type,no_of_claims
0,John Patel,34,Male,Ontario,820.00,0.00,3,car,0
2,Michael Singh,45,Male,Alberta,1100.25,0.00,8,home,0
4,David Brown,52,Male,Manitoba,1400.90,3000.00,10,health,4
6,Jason Lee,41,Male,Saskatchewan,1200.00,900.55,6,life,1
8,Robert Miller,56,Male,Alberta,1500.60,4500.80,9,health,5
10,Kevin Turner,31,Male,Ontario,720.10,0.00,2,life,0
11,Sophia Adams,36,Female,British Columbia,980.90,1500.25,5,home,3
12,Mark Wilson,43,Male,Quebec,1150.00,0.00,9,health,0
14,Ethan Davis,39,Male,Alberta,1020.75,600.40,4,life,1
16,Ryan Cooper,47,Male,Saskatchewan,1300.00,2000.00,8,car,4

In [101]:
# 7 Find Customer who have made at least 1 claim.
df.loc[df["claim_amount"]>0, "name"]

1          Sarah Wong
3        Priya Sharma
4         David Brown
6           Jason Lee
8       Robert Miller
9        Linda Garcia
11       Sophia Adams
14        Ethan Davis
16        Ryan Cooper
18       Daniel Evans
19     Maya Rodriguez
22      Noah Campbell
24     James Anderson
26       Logan Wright
28        Lucas Green
32        Jack Rivera
34     William Carter
36    Benjamin Hughes
38       Owen Russell
40        Elijah Ward
44       Wyatt Brooks
46       Andrew Price
Name: name, dtype: str

In [102]:
#8. Add new col premium per year

df["premium_per_year"] = (df["premium_amount"] / df["tenure_years"]).round(2)

In [103]:
df.head()

,name,age,gender,region,premium_amount,claim_amount,tenure_years,policy_type,no_of_claims,premium_per_year
0,John Patel,34,Male,Ontario,820.00,0.00,3,car,0,273.33
1,Sarah Wong,29,Female,British Columbia,650.50,1200.75,5,health,3,130.10
2,Michael Singh,45,Male,Alberta,1100.25,0.00,8,home,0,137.53
3,Priya Sharma,38,Female,Ontario,590.40,500.10,2,life,2,295.20
4,David Brown,52,Male,Manitoba,1400.90,3000.00,10,health,4,140.09

In [104]:
# 9 create a new colum hascalim which shows Yes if calaim anout >0 else no
df["has_claim"] = (df["claim_amount"] > 0).map({True: "Yes", False: "No"})

In [105]:
df.head()

,name,age,gender,region,premium_amount,claim_amount,tenure_years,policy_type,no_of_claims,premium_per_year,has_claim
0,John Patel,34,Male,Ontario,820.00,0.00,3,car,0,273.33,No
1,Sarah Wong,29,Female,British Columbia,650.50,1200.75,5,health,3,130.10,Yes
2,Michael Singh,45,Male,Alberta,1100.25,0.00,8,home,0,137.53,No
3,Priya Sharma,38,Female,Ontario,590.40,500.10,2,life,2,295.20,Yes
4,David Brown,52,Male,Manitoba,1400.90,3000.00,10,health,4,140.09,Yes

In [106]:
# 10. Filter customers who have health insurance nad live in albterta.

filters_rows = (df['policy_type']== 'health') &(df["region"]== "Alberta")
df.loc[filters_rows,["name","region","policy_type"]].head()

             name   region policy_type
8   Robert Miller  Alberta      health
21   Ava Thompson  Alberta      health

#### Medium(Agg, grouping, Renaming)

In [107]:
#11 Find the Avg premium amount by region.

df.groupby('region')['premium_amount'].agg(["mean"])

                         mean
region
Alberta           1176.556250
British Columbia   976.590000
Manitoba          1022.460000
Nova Scotia        916.800000
Ontario            760.206250
Quebec             815.914286
Saskatchewan      1307.850000

In [108]:
#12 find the total claim amount for each policytype.

df.groupby('policy_type')['claim_amount'].agg(["sum"])

                  sum
policy_type
car          14700.60
health        8701.55
home          1900.25
life         13802.60

In [109]:
#13 calculate the maximum tenure yeras for each gender.

df.groupby('gender')['tenure_years'].agg(["max"])

        max
gender
Female    7
Male     10

In [110]:
# 14 rename the column Premuim anount to premium-cad

df.rename(columns= {
    "premium_amount" :"premium_CAD"
}, inplace = True
)

In [111]:
df.head()

,name,age,gender,region,premium_CAD,claim_amount,tenure_years,policy_type,no_of_claims,premium_per_year,has_claim
0,John Patel,34,Male,Ontario,820.00,0.00,3,car,0,273.33,No
1,Sarah Wong,29,Female,British Columbia,650.50,1200.75,5,health,3,130.10,Yes
2,Michael Singh,45,Male,Alberta,1100.25,0.00,8,home,0,137.53,No
3,Priya Sharma,38,Female,Ontario,590.40,500.10,2,life,2,295.20,Yes
4,David Brown,52,Male,Manitoba,1400.90,3000.00,10,health,4,140.09,Yes

In [112]:
#15 Get the sum of premium amout and calim amt grouped by policty #type and region.
group_cols = ['policy_type','region']
cal_cols =['premium_CAD','claim_amount']
df.groupby(group_cols)[cal_cols].agg(["sum"])

                             premium_CAD claim_amount
                                     sum          sum
policy_type region
car         Alberta              1400.00      2800.50
            Nova Scotia          2030.30      3900.00
            Ontario              4530.50      1100.10
            Quebec                680.20         0.00
            Saskatchewan         4031.40      6900.00
health      Alberta              2140.85      4500.80
            British Columbia     1270.50      1200.75
            Manitoba             1400.90      3000.00
            Ontario              1980.25         0.00
            Quebec               3460.80         0.00
home        Alberta              1100.25         0.00
            British Columbia      980.90      1500.25
            Manitoba             1230.50         0.00
            Nova Scotia           720.10         0.00
            Ontario              3141.65         0.00
            Quebec               1570.40       400.00
life        Alberta              4771.35      5500.60
            British Columbia     2631.55      3500.60
            Manitoba             2480.90      2500.75
            Ontario              2510.90      1400.10
            Saskatchewan         1200.00       900.55

#### Advanced/ Multi -condition amd computation

In [113]:
#16 find customers whos premium amoutn is above the age for their policty type

df.loc[(df['premium_CAD'] > df.groupby('policy_type')['premium_CAD'].transform("mean")) ,"name"]

2       Michael Singh
4         David Brown
6           Jason Lee
8       Robert Miller
11       Sophia Adams
12        Mark Wilson
16        Ryan Cooper
18       Daniel Evans
19     Maya Rodriguez
20        Liam Parker
22      Noah Campbell
24     James Anderson
28        Lucas Green
30        Henry Young
34     William Carter
36    Benjamin Hughes
38       Owen Russell
40        Elijah Ward
45    Penelope Hughes
46       Andrew Price
Name: name, dtype: str

In [114]:
# 17 Find the top 3 customers with the highest Claim AMount
df_sorted = df.sort_values(by='claim_amount', ascending=False)

In [115]:
top3 = df_sorted["name"].head(3)
top3

8       Robert Miller
36    Benjamin Hughes
18       Daniel Evans
Name: name, dtype: str

In [116]:
#18 Create a new column risk level
# "high " if calim amount >2000
#"Meidium" if between 500 -2000
# "Low" otherwise
df["risk_level"] = df["claim_amount"].apply(
    lambda x: "High" if x > 2000
    else "Medium" if 500 <= x <= 2000
    else "Low"
)

In [117]:
df.head()

,name,age,gender,region,premium_CAD,claim_amount,tenure_years,policy_type,no_of_claims,premium_per_year,has_claim,risk_level
0,John Patel,34,Male,Ontario,820.00,0.00,3,car,0,273.33,No,Low
1,Sarah Wong,29,Female,British Columbia,650.50,1200.75,5,health,3,130.10,Yes,Medium
2,Michael Singh,45,Male,Alberta,1100.25,0.00,8,home,0,137.53,No,Low
3,Priya Sharma,38,Female,Ontario,590.40,500.10,2,life,2,295.20,Yes,Medium
4,David Brown,52,Male,Manitoba,1400.90,3000.00,10,health,4,140.09,Yes,High

In [120]:
#19 Filter cusotmer where
# tenure yeras >5 and
# no of calims > = 1 and
# policey type   ='life'


filter_conditons = (df['tenure_years'] >5) & (df['no_of_claims'] >= 1) & (df['policy_type'] == 'life')

df.loc[filter_conditons,["name","tenure_years","no_of_claims","policy_type"]]

              name  tenure_years  no_of_claims policy_type
6        Jason Lee             6             1        life
18    Daniel Evans            10             5        life
22   Noah Campbell             9             3        life
34  William Carter             8             4        life
38    Owen Russell             6             2        life
46    Andrew Price             8             3        life

In [128]:
#20 find whih region has the highest total premium amount overall.

region_totals = df.groupby("region")["premium_CAD"].sum().sort_values(ascending=False)

region_totals.head(1)

region
Ontario    12163.3
Name: premium_CAD, dtype: float64