##### Create a Pandas Series

In [20]:
from logging.config import stopListening
from statistics import multimode

import pandas as pd

data = {"Name": ["BIkesh","Treint"],
        "Address" :["Missi","Toront"]}


print(data)

my_series= pd.Series(data)

my_series

{'Name': ['BIkesh', 'Treint'], 'Address': ['Missi', 'Toront']}

Name       [BIkesh, Treint]
Address     [Missi, Toront]
dtype: object

In [21]:
df = pd.DataFrame(data)

df

     Name Address
0  BIkesh   Missi
1  Treint  Toront

In [28]:
import pandas as pd

grades = {"Sem1": 3.5,
"Sem2": 3.2,
"Sem3": 3.75,
"Sem4": 3.5 ,
"Sem" : 3.8}

my_series = pd.Series(grades)

my_series

Sem1    3.50
Sem2    3.20
Sem3    3.75
Sem4    3.50
Sem     3.80
dtype: float64

In [34]:
my_series.tail(2)

Sem4    3.5
Sem     3.8
dtype: float64

In [1]:
my_series.head()

NameError: name 'my_series' is not defined

In [36]:
avg_score = my_series.mean()

In [38]:
my_series.sum()

np.float64(17.75)

In [39]:
my_series.max()

np.float64(3.8)

In [49]:
print(my_series.min())

3.2

In [41]:
my_series.value_counts()

3.50    2
3.20    1
3.75    1
3.80    1
Name: count, dtype: int64

In [46]:
my_series.unique()

array([3.5 , 3.2 , 3.75, 3.8 ])

In [43]:
my_series.duplicated()

Sem1    False
Sem2    False
Sem3    False
Sem4     True
Sem     False
dtype: bool

In [44]:
my_series.describe()

count    5.000000
mean     3.550000
std      0.239792
min      3.200000
25%      3.500000
50%      3.500000
75%      3.750000
max      3.800000
dtype: float64

In [47]:
my_series.sort_values()

Sem2    3.20
Sem1    3.50
Sem4    3.50
Sem3    3.75
Sem     3.80
dtype: float64

In [48]:
my_series.sort_index()

Sem     3.80
Sem1    3.50
Sem2    3.20
Sem3    3.75
Sem4    3.50
dtype: float64

In [ ]:
my_series.apply()

In [50]:
#Question 1
temps = [30,32,31,29,35,33]

label = ['Mon','Tue','Wed','Thu','Fri','Sat']

temp_series = pd.Series(temps, index = label)
print(temp_series["Wed"])
print(temp_series.mean())

In [75]:
#Question 2

scores = pd.Series([75,82,91,68,87,90], index =['Alice','Bob','Charlie','David','Eve','Frank'])

print(scores[scores > 80])
print(scores[scores>=70].nunique())

Bob        82
Charlie    91
Eve        87
Frank      90
dtype: int64
5

In [64]:
print(scores[scores >80])

Bob        82
Charlie    91
Eve        87
Frank      90
dtype: int64

In [74]:
scores[scores>=70].nunique()

5

In [77]:
# covert scores to grades
def covert_to_grade(scores):
    if scores >= 90 :
        return 'A'
    elif 80 <= scores <= 89:
        return 'B'
    elif 70 <= scores <= 79:
        return 'C'
    elif 50 <= scores <= 69:
        return 'D'
    return 'F'

scores.apply(covert_to_grade)

Alice      C
Bob        B
Charlie    A
David      D
Eve        B
Frank      A
dtype: str

In [78]:
scores

Alice      75
Bob        82
Charlie    91
David      68
Eve        87
Frank      90
dtype: int64

In [9]:
import pandas as pd

data = {
        'Name':['John','Alice','Bob'],
        'Age' :[25,27,36],
        'City':['Paris','Toronto','New York']
}

df = pd.DataFrame(data)
df

    Name  Age      City
0   John   25     Paris
1  Alice   27   Toronto
2    Bob   36  New York

In [10]:
df['Name']

0     John
1    Alice
2      Bob
Name: Name, dtype: str

In [11]:
df.describe()

             Age
count   3.000000
mean   29.333333
std     5.859465
min    25.000000
25%    26.000000
50%    27.000000
75%    31.500000
max    36.000000

In [12]:
df.value_counts()

Name   Age  City
John   25   Paris       1
Alice  27   Toronto     1
Bob    36   New York    1
Name: count, dtype: int64

In [14]:
df.nunique()

Name    3
Age     3
City    3
dtype: int64

In [26]:
data= [
        ['Name','Age','City'],
        ['Alice',25,'New York'],
        ['BOB',34,'London'],
        ['chralter',28,'Paris']
]

df= pd.DataFrame(data)

df

          0    1         2
0      Name  Age      City
1     Alice   25  New York
2       BOB   34    London
3  chralter   28     Paris

In [24]:
#csv, xlsx, pdf, py, txt, ipynb

# import pandas as pd
#
# df= pd.read_csv('Absolute file path')

<>:5: SyntaxWarning: invalid escape sequence '\P'
<>:5: SyntaxWarning: invalid escape sequence '\P'
C:\Users\bkies\AppData\Local\Temp\ipykernel_34260\3599548078.py:5: SyntaxWarning: invalid escape sequence '\P'
  df= pd.read_csv('C:\\Users\\bkies\PycharmProjects\PythonProject\student_info.csv')

   Name     Address  Level
0   Tom     Toronto     12
1  Emma  North York     10

In [25]:
df

   Name     Address  Level
0   Tom     Toronto     12
1  Emma  North York     10

In [32]:
data = {
        'Name':['John','Alice','Bob','Charli'],
        'Age' :[25,27,36,34],
        'City':['Paris','Toronto','New York','London']
}

df = pd.DataFrame(data)
df

     Name  Age      City
0    John   25     Paris
1   Alice   27   Toronto
2     Bob   36  New York
3  Charli   34    London

In [33]:
df.set_index('Name',inplace= True)

In [34]:
df

        Age      City
Name
John     25     Paris
Alice    27   Toronto
Bob      36  New York
Charli   34    London

In [37]:
df.loc['Charli']

Age         34
City    London
Name: Charli, dtype: object

In [38]:
df.reset_index()

     Name  Age      City
0    John   25     Paris
1   Alice   27   Toronto
2     Bob   36  New York
3  Charli   34    London

In [53]:

df_2 = pd.DataFrame(data)

In [54]:
df_2

     Name  Age      City
0    John   25     Paris
1   Alice   27   Toronto
2     Bob   36  New York
3  Charli   34    London

In [55]:
step = 10
start_value = min(list(df_2.index.values)) +100
end_value = ((max(list(df_2.index.values))+1) * step) +100

index_range = pd.RangeIndex(start = start_value, stop = end_value, step = step)
df_2 = pd.DataFrame(data , index = index_range)

df_2

       Name  Age      City
100    John   25     Paris
110   Alice   27   Toronto
120     Bob   36  New York
130  Charli   34    London

In [51]:
df_2.loc[100]

Name     John
Age        25
City    Paris
Name: 100, dtype: object

In [3]:
print('Hi')

Hi

In [2]:
#Practice Test for class


import pandas as pd

data = {
    'CustomerID': [101, 102, 103, 101, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'David'],
    'OrderAmount': [250, 450, 300, 250, 500]
}

df = pd.DataFrame(data)

In [3]:
df

   CustomerID     Name  OrderAmount
0         101    Alice          250
1         102      Bob          450
2         103  Charlie          300
3         101    Alice          250
4         104    David          500

In [9]:
# add the column "DiscountedAmount"
rate = 10
values = [(x - x *(rate/100)) for x in df["OrderAmount"] ]

In [10]:
values

[225.0, 405.0, 270.0, 225.0, 450.0]

In [11]:
df["DiscountAmount"] = values

In [12]:
df

   CustomerID     Name  OrderAmount  DiscountAmount
0         101    Alice          250           225.0
1         102      Bob          450           405.0
2         103  Charlie          300           270.0
3         101    Alice          250           225.0
4         104    David          500           450.0

In [14]:
df.drop("Name",axis = 1 ,inplace = True)

In [15]:
df

   CustomerID  OrderAmount  DiscountAmount
0         101          250           225.0
1         102          450           405.0
2         103          300           270.0
3         101          250           225.0
4         104          500           450.0

In [18]:
df.drop_duplicates("CustomerID",keep = "last", inplace = True)

In [19]:
df

   CustomerID  OrderAmount  DiscountAmount
0         101          250           225.0
1         102          450           405.0
2         103          300           270.0
4         104          500           450.0

In [21]:
#Problem 1

In [22]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [24, 30, 35, 40],
        'City': ['New York', 'Toronto', 'London', 'Sydney']}

In [23]:
df = pd.DataFrame(data)

In [24]:
df

      Name  Age      City
0    Alice   24  New York
1      Bob   30   Toronto
2  Charlie   35    London
3    David   40    Sydney

In [26]:
#problem 2: Basic Data Frame Operations
#display only the Name and city columns
df.loc[:,['Name','City']]

      Name      City
0    Alice  New York
1      Bob   Toronto
2  Charlie    London
3    David    Sydney

In [27]:
df.loc[df['Age'] >30]

      Name  Age    City
2  Charlie   35  London
3    David   40  Sydney

In [28]:
#problem 3: Adding and Deleteing columns

salary_values = [70000,80000,120000,95000]
df['Salary'] = salary_values

In [29]:
df

      Name  Age      City  Salary
0    Alice   24  New York   70000
1      Bob   30   Toronto   80000
2  Charlie   35    London  120000
3    David   40    Sydney   95000

In [31]:
df.drop(columns="City", inplace= True)

In [32]:
df

      Name  Age  Salary
0    Alice   24   70000
1      Bob   30   80000
2  Charlie   35  120000
3    David   40   95000